services:
  mysql:
    image: mysql:8.4
    restart: always
    container_name: mysql-projeto-biblioteca
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
    ports: 
      - '3336:3306'
    networks: 
      - biblioteca-network
networks:
  biblioteca-network:
    driver: bridge